import Link from "next/link";
import { ArrowLeft, CheckCircle2 } from "lucide-react";
import { notFound } from "next/navigation";
import { addCustomerAddressAction, submitCustomerSupportAction, updateCustomerPersonalAction, updateCustomerPreferencesAction } from "@/app/customer/actions";
import { requireCustomerSession } from "@/lib/customer/auth";
import { SOUTH_AFRICAN_PROVINCES } from "@/lib/customer/validation";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const sections = ["personal", "addresses", "notifications", "privacy", "categories", "filters", "appearance", "language", "help", "support", "about"] as const;
type Section = typeof sections[number];
const titles: Record<Section, string> = { personal: "Personal Information", addresses: "Addresses", notifications: "Notifications", privacy: "Privacy & Security", categories: "Favourite Categories", filters: "Default Filters", appearance: "App Appearance", language: "Language", help: "Help & FAQ", support: "Contact Support", about: "About GreenChoice" };
const input = "mt-2 h-12 w-full rounded-xl border-2 border-[#d7e1da] bg-white px-4 outline-none focus:border-[#0b8a40]";
const panel = "rounded-2xl border-2 border-[#dce5df] bg-white p-5";

function SaveButton({ label = "Save changes" }: { label?: string }) { return <button className="mt-5 inline-flex h-12 items-center justify-center rounded-xl bg-[#087c39] px-6 font-black text-white"><CheckCircle2 className="mr-2" size={19} />{label}</button>; }

export default async function CustomerProfileSectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section: rawSection } = await params;
  if (!sections.includes(rawSection as Section)) notFound();
  const section = rawSection as Section;
  const session = await requireCustomerSession();
  const supabase = await createSupabaseServerClient();
  const [{ data: preferences }, { data: addresses }, { data: categories }, { data: supportRequests }] = await Promise.all([
    supabase!.from("customer_preferences").select("*").eq("user_id", session.user.id).maybeSingle(),
    supabase!.from("customer_addresses").select("*").eq("user_id", session.user.id).order("is_default", { ascending: false }),
    supabase!.from("categories").select("slug,name").eq("is_active", true).order("sort_order"),
    supabase!.from("customer_support_requests").select("id,subject,status,created_at").eq("user_id", session.user.id).order("created_at", { ascending: false }).limit(10)
  ]);

  return (
    <main className="mx-auto min-h-screen max-w-2xl px-4 py-7 sm:px-6">
      <Link href="/customer/profile" className="inline-flex items-center gap-2 font-black text-[#087c39]"><ArrowLeft size={19} /> Profile</Link>
      <h1 className="mt-5 text-3xl font-black">{titles[section]}</h1>

      {section === "personal" ? <form action={updateCustomerPersonalAction} className={`${panel} mt-6 grid gap-4 sm:grid-cols-2`}><label className="font-bold">Name<input className={input} name="firstName" defaultValue={session.profile.first_name} required /></label><label className="font-bold">Surname<input className={input} name="surname" defaultValue={session.profile.surname} required /></label><label className="font-bold sm:col-span-2">Email address<input className={`${input} bg-[#f2f4f2]`} value={session.profile.email} readOnly /></label><label className="font-bold sm:col-span-2">Phone number<input className={input} name="phoneNumber" defaultValue={session.profile.phone_number} required /></label><div className="sm:col-span-2 rounded-xl bg-[#f2f7f3] p-4 text-sm text-[#55645a]">Date of birth: {new Intl.DateTimeFormat("en-ZA", { dateStyle: "long" }).format(new Date(`${session.profile.date_of_birth}T00:00:00Z`))}<br />ID number ending in {session.profile.id_last_four}. Your complete ID number is not displayed or stored here.</div><div className="sm:col-span-2"><SaveButton /></div></form> : null}

      {section === "addresses" ? <><div className="mt-6 grid gap-3">{(addresses ?? []).map((address) => <article key={address.id} className={panel}><div className="flex items-center justify-between"><strong>{address.label}</strong>{address.is_default ? <span className="rounded-full bg-[#e1f5e7] px-3 py-1 text-xs font-black text-[#087c39]">Default</span> : null}</div><p className="mt-2 text-[#617067]">{[address.street_address, address.unit_details, address.suburb, address.city, address.province, address.postal_code].filter(Boolean).join(", ")}</p></article>)}{!addresses?.length ? <p className={panel}>No addresses saved.</p> : null}</div><form action={addCustomerAddressAction} className={`${panel} mt-6 grid gap-4 sm:grid-cols-2`}><h2 className="text-xl font-black sm:col-span-2">Add an address</h2><label className="font-bold">Label<input className={input} name="label" defaultValue="Home" required /></label><label className="font-bold">Street address<input className={input} name="streetAddress" required /></label><label className="font-bold">Unit or complex<input className={input} name="unitDetails" /></label><label className="font-bold">Suburb<input className={input} name="suburb" required /></label><label className="font-bold">City<input className={input} name="city" required /></label><label className="font-bold">Province<select className={input} name="province" defaultValue="Gauteng">{SOUTH_AFRICAN_PROVINCES.map((province) => <option key={province}>{province}</option>)}</select></label><label className="font-bold">Postal code<input className={input} name="postalCode" pattern="[0-9]{4}" required /></label><div className="sm:col-span-2"><SaveButton label="Add address" /></div></form></> : null}

      {section === "notifications" ? <form action={updateCustomerPreferencesAction} className={`${panel} mt-6 grid gap-4`}><input type="hidden" name="preferenceScope" value="notifications" /><label className="flex items-center justify-between gap-4 font-bold"><span>Email account updates</span><input className="size-5 accent-[#087c39]" type="checkbox" name="emailNotifications" defaultChecked={preferences?.email_notifications ?? true} /></label><label className="flex items-center justify-between gap-4 font-bold"><span>SMS account updates</span><input className="size-5 accent-[#087c39]" type="checkbox" name="smsNotifications" defaultChecked={preferences?.sms_notifications ?? true} /></label><label className="flex items-center justify-between gap-4 font-bold"><span>Promotional updates</span><input className="size-5 accent-[#087c39]" type="checkbox" name="promotionalNotifications" defaultChecked={preferences?.promotional_notifications ?? false} /></label><SaveButton /></form> : null}

      {section === "privacy" ? <div className={`${panel} mt-6 grid gap-4`}><div><h2 className="font-black">Password and account recovery</h2><p className="mt-1 text-sm text-[#637168]">Use GreenChoice’s secure password-reset process. Successful resets revoke the previous sign-in session.</p><Link href="/forgot-password" className="mt-3 inline-flex rounded-xl bg-[#087c39] px-5 py-3 font-black text-white">Change or reset password</Link></div><div className="border-t-2 border-[#edf1ee] pt-4"><h2 className="font-black">Your privacy documents</h2><div className="mt-3 flex flex-wrap gap-3"><Link href={"/legal/terms-of-service.pdf" as never} target="_blank" className="rounded-xl border-2 border-[#cfdad2] px-4 py-2 font-bold">Terms</Link><Link href={"/legal/privacy-policy.pdf" as never} target="_blank" className="rounded-xl border-2 border-[#cfdad2] px-4 py-2 font-bold">Privacy Policy</Link></div></div><div className="border-t-2 border-[#edf1ee] pt-4"><h2 className="font-black">Identity protection</h2><p className="mt-1 text-sm text-[#637168]">GreenChoice stores only your verified birth date, a protected duplicate-check fingerprint and the final four digits of your ID—not the complete ID number.</p></div></div> : null}

      {section === "categories" ? <form action={updateCustomerPreferencesAction} className={`${panel} mt-6`}><input type="hidden" name="preferenceScope" value="categories" /><p className="mb-4 text-[#637168]">Choose real categories currently available in GreenChoice.</p><div className="grid gap-3 sm:grid-cols-2">{(categories ?? []).map((category) => <label key={category.slug} className="flex items-center gap-3 rounded-xl border-2 border-[#dce5df] p-4 font-bold"><input className="size-5 accent-[#087c39]" type="checkbox" name="favouriteCategories" value={category.slug} defaultChecked={(preferences?.favourite_categories ?? []).includes(category.slug)} />{category.name}</label>)}</div><SaveButton /></form> : null}

      {section === "filters" ? <form action={updateCustomerPreferencesAction} className={`${panel} mt-6`}><input type="hidden" name="preferenceScope" value="filters" /><label className="font-bold">Default search radius (km)<input className={input} type="number" name="defaultRadius" min="1" max="100" defaultValue={preferences?.default_radius_km ?? 15} /></label><label className="mt-4 flex items-center justify-between gap-4 font-bold"><span>Show open stores first</span><input className="size-5 accent-[#087c39]" type="checkbox" name="openNowOnly" defaultChecked={preferences?.open_now_only ?? false} /></label><SaveButton /></form> : null}

      {section === "appearance" ? <form action={updateCustomerPreferencesAction} className={`${panel} mt-6`}><input type="hidden" name="preferenceScope" value="appearance" /><div className="grid gap-3">{["light", "dark", "system"].map((appearance) => <label key={appearance} className="flex items-center gap-3 rounded-xl border-2 border-[#dce5df] p-4 font-bold capitalize"><input className="size-5 accent-[#087c39]" type="radio" name="appearance" value={appearance} defaultChecked={(preferences?.appearance ?? "system") === appearance} />{appearance}</label>)}</div><SaveButton /></form> : null}

      {section === "language" ? <form action={updateCustomerPreferencesAction} className={`${panel} mt-6`}><input type="hidden" name="preferenceScope" value="language" /><label className="font-bold">Language<select className={input} name="language" defaultValue="en-ZA"><option value="en-ZA">English (South Africa)</option></select></label><p className="mt-3 text-sm text-[#637168]">Additional languages can be added without changing your account.</p><SaveButton /></form> : null}

      {section === "help" ? <div className="mt-6 grid gap-3">{[["How do I add a product?", "Open a store, choose a category and select Add to cart on an available product."], ["Why can’t I mix stores?", "Each checkout list is scoped to one store so prices and stock remain correct."], ["Does checkout place an order?", "Not yet. The first version saves your selected products and calculates the total only."], ["What if I forget my password?", "Use Forgot Password on the GreenChoice sign-in screen."]].map(([question, answer]) => <details key={question} className={panel}><summary className="cursor-pointer font-black">{question}</summary><p className="mt-3 text-[#637168]">{answer}</p></details>)}</div> : null}

      {section === "support" ? <><form action={submitCustomerSupportAction} className={`${panel} mt-6 grid gap-4`}><label className="font-bold">Category<select className={input} name="category"><option value="account">Account</option><option value="technical">Technical</option><option value="store">Store</option><option value="privacy">Privacy</option><option value="other">Other</option></select></label><label className="font-bold">Subject<input className={input} name="subject" required /></label><label className="font-bold">Message<textarea className="mt-2 min-h-36 w-full rounded-xl border-2 border-[#d7e1da] p-4 outline-none focus:border-[#0b8a40]" name="message" minLength={10} maxLength={2000} required /></label><SaveButton label="Submit request" /></form>{supportRequests?.length ? <section className="mt-6"><h2 className="mb-3 text-xl font-black">Your requests</h2><div className="grid gap-3">{supportRequests.map((request) => <article key={request.id} className={panel}><div className="flex justify-between gap-4"><strong>{request.subject}</strong><span className="capitalize text-[#087c39]">{request.status.replace("_", " ")}</span></div></article>)}</div></section> : null}</> : null}

      {section === "about" ? <div className={`${panel} mt-6`}><p className="text-sm font-black uppercase tracking-[0.18em] text-[#0a8840]">GreenChoice</p><h2 className="mt-2 text-2xl font-black">Customer browsing</h2><p className="mt-3 text-[#637168]">GreenChoice connects customer browsing to the same live store, product and inventory information used by participating GreenChoice workstations. This version does not activate online payment, delivery or order placement.</p><div className="mt-5 flex flex-wrap gap-3"><Link href={"/legal/terms-of-service.pdf" as never} target="_blank" className="rounded-xl border-2 border-[#cfdad2] px-4 py-2 font-bold">Terms</Link><Link href={"/legal/privacy-policy.pdf" as never} target="_blank" className="rounded-xl border-2 border-[#cfdad2] px-4 py-2 font-bold">Privacy Policy</Link></div></div> : null}
    </main>
  );
}
